apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-web
  namespace: harness-delegate-ng
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-web
  template:
    metadata:
      labels:
        app: harness-web
    spec:
      containers:
      - name: harness-web
        image: docker.io/zinzuwad/test-repo-images:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: harness-web-service
  namespace: harness-delegate-ng
spec:
  selector:
    app: harness-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
